### PR TITLE
add cross-table ID to hierarchical micro data

### PR DESCRIPTION
**Pull request by mpadge**
hey @gergness, sorry about total lack of contribution to date. excuses, excuses, blah blah, but first things first: Congratulations on pulling together an amazing, and amazingly well-coded, package! You've really done a brilliant job. I particularly like the way you first read in the binary data into R and then pass (the implicit pointer to) that to the C++ routines - sure, it might be marginally more efficient to do the whole shebang in C++, but you gain so much more flexibility your way. It really is very clever.

Motivation for the PR: It appears to me - and it is very likely that i may be wrong here, so please let me know if so! - that it is not currently possible to cross-reference hierarchical micro data, because the tables contain no way to match entries. This PR is an attempt by me to implement one way of achieving this, by way of a shared "ID" variable. I'm very happy to have a conversation here before you accept this PR, particularly if I have actually misunderstood the results of `read_ipums_micro_list` - just let me know.

My current way of looking at this:
```
dat <- read_ipums_micro_list (ipums_example("cps_00010.xml")) 
```
How do I match variables in `dat$PERSON` to corresponding ones in `dat$HOUSEHOLD`? For example, what is the `STATEFIP` OF `dat$PERSON [1, ]`? Such matching is necessary to actually analyse the data in a hierarchical fashion, right?

The PR can also be re-phrased in direct R terms: I've attempted to create a variable that can be used directly for `dplyr` table joins, because it seems to me that current tables do not have any variables with which to do this?

-------

I also had a play around with efficiency gains in `read_hier_list.cpp`, by way of properly pre-allocating your `out` array (your comment about you being, "not sure if this is a performant way to do this"), but it didn't bring anything. The info you need to pre-allocate can't be extracted efficiently from `readr::read_lines_raw`, and real efficiency gains would only be possible by doing this in C++, at the expense of the aforementioned loss of flexibility.

### CODE REVIEW

**Comment by gergness** [comment]
Ha, thanks for the kind words and for looking through the code!

In the CPS example above, the variable `SERIAL` is the cross table ID and it is available on both datasets. As I learn more about how different projects are set up here though, I wouldn't be surprised if some projects don't provide the linking variable for both datasets in the data we post publicly.

Let me look into whether there are projects that don't provide the linking variable, because our rectype structure is a little more complicated than what this PR allows for currently if I understand everything correctly. For example, our Time Use data has more than 2 rectypes, and this PR will only link from the top level rectype to the ones below it.

Also, can you help me understand how the C++11 dependency affects us? Are users who install via CRAN binaries affected at all?

**Comment by mpadge** [comment]
Ah yeah, now I see the `SERIAL` variable. However, I recently downloaded an MTUS data set that had no such linking variable. This obviously complicates the issue, because we'd first need to check whether there was a linking variable. For that you'd have to know more about data sets which generated them, and in each case, what they were called.

And yes, you're also right about only linking down one level. I meant to comment on that, but forgot. I simply didn't know whether there were any hierarchical data with more than two levels. The PR as stands will link from any and all top level tables to all tables one level below. If there are greater depths of hierarchy, then modification would obviously be necessary.

Finally, C++11 should affect nothing - I have that on pretty much all of my packages which pass all CRAN tests. It's just necessary for the `to_string` function, but that could easily be replaced by an `sprintf` statement.

**Comment by gergness** [comment]
Do the variables `HLDID` and `PERSID` exist in your extract? (and if they do, are they useful for linking?). I just made an MTUS extract for France 1988, and I think that's what is intended.

I'm hopefully going to meet with the Time Use group to discuss, but I think that there already always is a link between all records and the top level rectype. If this is true, I'm not sure your PR as it exists is needed. However, when there are multiple levels (in ATUS, there are 5 rectypes, with at least 3 nesting levels if not 4 or 5), I don't think it's always possible to link to the parent.

**Comment by mpadge** [comment]
ah yeah, those variables are there. I guess it's my fault for not having perused the "ddi" in sufficient detail. They have to be explicitly entered in `vars`, but then all is good. I guess it'd be nice to have any cross-table variables automatically extracted to avoid this confusion, but that's a tiny and separate issue to this PR, so I'll close now. Thanks anyway!

**Pull request closed without merging**
